-- ==========================================
-- DJANGO MIGRATIONS
-- ==========================================
CREATE TABLE django_migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    applied TIMESTAMPTZ NOT NULL
);

-- ==========================================
-- DJANGO CONTENT TYPES
-- ==========================================
CREATE TABLE django_content_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL
);

-- ==========================================
-- AUTH PERMISSION
-- ==========================================
CREATE TABLE auth_permission (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    content_type_id INTEGER NOT NULL,
    codename VARCHAR(100) NOT NULL,

    CONSTRAINT fk_auth_permission_content_type
        FOREIGN KEY (content_type_id)
        REFERENCES django_content_type(id)
);

-- ==========================================
-- AUTH GROUP
-- ==========================================
CREATE TABLE auth_group (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

-- ==========================================
-- AUTH GROUP PERMISSIONS
-- ==========================================
CREATE TABLE auth_group_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,

    CONSTRAINT fk_agp_group
        FOREIGN KEY (group_id)
        REFERENCES auth_group(id),

    CONSTRAINT fk_agp_permission
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission(id)
);

-- ==========================================
-- AUTH USER
-- ==========================================
CREATE TABLE auth_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    last_login TIMESTAMPTZ NULL,
    is_superuser BOOLEAN NOT NULL,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    is_staff BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    date_joined TIMESTAMPTZ NOT NULL
);

-- ==========================================
-- AUTH USER GROUPS
-- ==========================================
CREATE TABLE auth_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,

    CONSTRAINT fk_aug_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id),

    CONSTRAINT fk_aug_group
        FOREIGN KEY (group_id)
        REFERENCES auth_group(id)
);

-- ==========================================
-- AUTH USER USER PERMISSIONS
-- ==========================================
CREATE TABLE auth_user_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,

    CONSTRAINT fk_auup_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id),

    CONSTRAINT fk_auup_permission
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission(id)
);

-- ==========================================
-- DJANGO ADMIN LOG
-- ==========================================
CREATE TABLE django_admin_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time TIMESTAMPTZ NOT NULL,
    object_id TEXT NULL,
    object_repr VARCHAR(200) NOT NULL,
    action_flag SMALLINT NOT NULL,
    change_message TEXT NOT NULL,
    content_type_id INTEGER NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_dal_content_type
        FOREIGN KEY (content_type_id)
        REFERENCES django_content_type(id),

    CONSTRAINT fk_dal_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id)
);

-- ==========================================
-- DJANGO SESSION
-- ==========================================
CREATE TABLE django_session (
    session_key VARCHAR(40) PRIMARY KEY,
    session_data TEXT NOT NULL,
    expire_date TIMESTAMPTZ NOT NULL
);

-- ==========================================
-- PATIENTS PATIENT
-- ==========================================
CREATE TABLE patients_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    edad INTEGER NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    peso DOUBLE PRECISION NOT NULL,
    altura DOUBLE PRECISION NOT NULL,
    imc DOUBLE PRECISION NOT NULL,
    glucosa DOUBLE PRECISION NOT NULL,
    colesterol DOUBLE PRECISION NOT NULL,
    riesgo VARCHAR(100) NOT NULL,
    fecha_consulta DATE NULL,
    created_at TIMESTAMPTZ NOT NULL,
    diagnostico TEXT NULL,
    documento VARCHAR(50) UNIQUE,
    es_diabetico BOOLEAN NOT NULL,
    es_fumador BOOLEAN NOT NULL,
    es_hipertenso BOOLEAN NOT NULL,
    presion_diastolica INTEGER NOT NULL,
    presion_sistolica INTEGER NOT NULL,
    saturacion_oxigeno DOUBLE PRECISION NOT NULL,
    frecuencia_cardiaca INTEGER NOT NULL
);

-- ==========================================
-- ETL UPLOADED DATASET
-- ==========================================
CREATE TABLE etl_uploadeddataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    stored_path VARCHAR(500) NOT NULL,
    rows_received INTEGER NOT NULL,
    rows_processed INTEGER NOT NULL,
    rows_inserted INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    notes TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NULL,
    execution_time DOUBLE PRECISION NOT NULL,
    user_id INTEGER NULL,
    file_hash VARCHAR(255) NULL,

    CONSTRAINT fk_uploadeddataset_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id)
);

-- ==========================================
-- PATIENT AUDIT
-- ==========================================
CREATE TABLE patients_patientaudit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    changes JSONB NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    patient_id BIGINT NOT NULL,
    user_id INTEGER NULL,

    CONSTRAINT fk_patientaudit_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients_patient(id),

    CONSTRAINT fk_patientaudit_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id)
);

-- ==========================================
-- ÍNDICES RECOMENDADOS
-- ==========================================

CREATE INDEX idx_patient_documento
    ON patients_patient(documento);

CREATE INDEX idx_patient_created_at
    ON patients_patient(created_at);

CREATE INDEX idx_patientaudit_patient
    ON patients_patientaudit(patient_id);

CREATE INDEX idx_patientaudit_timestamp
    ON patients_patientaudit(timestamp);

CREATE INDEX idx_uploadeddataset_user
    ON etl_uploadeddataset(user_id);

CREATE INDEX idx_session_expire_date
    ON django_session(expire_date);