# Generated by Django 6.0 on 2026-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=255)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Procesado'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archivo cargado',
                'verbose_name_plural': 'Archivos cargados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
