# Generated by Django 6.0.5 on 2026-06-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_uploadeddataset_execution_time_uploadeddataset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
