# Generated by Django 6.0 on 2026-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('riesgo', models.CharField(choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], max_length=20)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
