# Generated by Django 6.0 on 2026-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
