# Generated by Django 6.0 on 2026-06-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_diagnostico_patient_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='es_diabetico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='es_fumador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='es_hipertenso',
            field=models.BooleanField(default=False),
        ),
    ]
