# Generated by Django 6.0 on 2026-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_es_diabetico_patient_es_fumador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='presion_diastolica',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='patient',
            name='presion_sistolica',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='saturacion_oxigeno',
            field=models.FloatField(default=95),
        ),
    ]
