# Generated by Django 6.0 on 2026-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_presion_diastolica_patient_presion_sistolica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=75),
        ),
    ]
