# Generated by Django 6.0.5 on 2026-06-13 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_patientaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(default='Random Forest Classifier', max_length=50)),
                ('training_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_records', models.IntegerField(default=0)),
                ('training_records', models.IntegerField(default=0)),
                ('test_records', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision_macro', models.FloatField(default=0.0)),
                ('recall_macro', models.FloatField(default=0.0)),
                ('f1_macro', models.FloatField(default=0.0)),
                ('confusion_matrix_image', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicted_risk', models.CharField(choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], max_length=20)),
                ('actual_risk', models.CharField(blank=True, choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], max_length=20, null=True)),
                ('probability', models.FloatField(default=0.0)),
                ('input_data', models.JSONField(default=dict)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
